// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package devport

import (
	"github.com/google/wire"
)

import (
	_ "modernc.org/sqlite"
)

// Injectors from wire.go:

func InitializeManager(runtime RuntimeConfig, managerIO ManagerIO) (*Manager, error) {
	paths, err := ProvidePaths(runtime)
	if err != nil {
		return nil, err
	}
	config, err := ProvideConfig(paths)
	if err != nil {
		return nil, err
	}
	store, err := ProvideStore(paths)
	if err != nil {
		return nil, err
	}
	tmux := ProvideTmux(config)
	logger := ProvideManagerLogger()
	string2, err := ProvideExecutable()
	if err != nil {
		return nil, err
	}
	manager := NewManagerFromDeps(runtime, managerIO, paths, config, store, tmux, logger, string2)
	return manager, nil
}

// wire.go:

var ManagerProviderSet = wire.NewSet(
	ProvidePaths,
	ProvideConfig,
	ProvideStore,
	ProvideExecutable,
	ProvideTmux,
	ProvideManagerLogger,
	NewManagerFromDeps,
)
