// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package devport

import (
	"github.com/google/wire"
)

import (
	_ "modernc.org/sqlite"
)

// Injectors from wire.go:

func InitializeManager(runtime RuntimeConfig, managerIO ManagerIO) (*Manager, error) {
	runtime2, err := ProvideRuntime(runtime, managerIO)
	if err != nil {
		return nil, err
	}
	store, err := ProvideStore(runtime2)
	if err != nil {
		return nil, err
	}
	tmux := ProvideTmux(runtime2)
	logger := ProvideManagerLogger()
	string2, err := ProvideExecutable()
	if err != nil {
		return nil, err
	}
	manager := NewManagerFromDeps(runtime2, store, tmux, logger, string2)
	return manager, nil
}

// wire.go:

var ManagerProviderSet = wire.NewSet(
	ProvideRuntime,
	ProvideStore,
	ProvideExecutable,
	ProvideTmux,
	ProvideManagerLogger,
	NewManagerFromDeps,
)
