// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/google/wire"
	"github.com/hayeah/devportv2"
)

// Injectors from wire.go:

func InitializeApp(managerIO devport.ManagerIO) *App {
	managerFactory := NewManagerFactory(managerIO)
	app := NewApp(managerFactory, managerIO)
	return app
}

// wire.go:

var AppProviderSet = wire.NewSet(
	NewManagerFactory,
	NewApp,
)
